[config]

[templates.waybar]
input_path = "templates/waybar-colors3.css"
output_path = "~/.config/waybar/colors.css"

[templates.rofi]
input_path = "templates/rofi-colors.css"
output_path = "~/.config/rofi/colors.rasi"

[templates.hypr]
input_path = "templates/hyprland-colors.lua"
output_path = "~/.config/hypr/modules/colors.lua"
