local vars = require("modules.vars")

 hl.on("hyprland.start", function () 
   hl.exec_cmd("hyprlock")
   hl.exec_cmd(vars.bar)
   hl.exec_cmd("swayosd-server")
   hl.exec_cmd("wl-paste --type text --watch cliphist store")
   hl.exec_cmd("wl-paste --type image --watch cliphist store")
   hl.exec_cmd("swaync")
   hl.exec_cmd("hypridle")
   --hl.exec_cmd("waybar & hyprpaper & firefox")
 end)
