# vim:fileencoding=utf-8:foldmethod=marker

include matugen.conf

# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

font_size 11.0

#: Text cursor customization {{{

cursor_shape beam

cursor_shape_unfocused hollow

cursor_blink_interval 0
cursor_trail 0

#: }}}

#: Scrollback {{{

scrollback_lines 10000

#: }}}

#: Mouse {{{

url_style curly
detect_urls yes
strip_trailing_spaces smart
copy_on_select yes

#: }}}

#: Terminal bell {{{

enable_audio_bell yes

visual_bell_duration 0.0

#: Window layout {{{

remember_window_size  no

window_padding_width 0

confirm_os_window_close 0

#: Tab bar {{{

tab_bar_edge top


tab_bar_style powerline

tab_bar_min_tabs 2

tab_title_max_length 20

tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{secure_input_symbol}{fmt.fg.tab}{tab.last_focused_progress_percent}{title}"

# shell .

# editor .
#: The default value of . means to use the environment variables
#: VISUAL and EDITOR in that order. If these variables aren't set,
#: kitty will run your shell ($SHELL -l -i -c env) to see if your
#: shell startup rc files set VISUAL or EDITOR. If that doesn't work,
#: kitty will cycle through various known editors (vim, emacs, etc.)
#: and take the first one that exists on your system.

shell_integration enabled

map ctrl+n launch --type=os-window --cwd=current
